# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-ecr
  description: This component is responsible for provisioning repositories, lifecycle rules, and permissions for streamlined ECR usage
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component

